"""role changed to boolean and profile pic not having default value

Revision ID: 8b2db5827f00
Revises: 
Create Date: 2026-02-25 18:34:39.164155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b2db5827f00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE BOOLEAN USING role::boolean')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE users ALTER COLUMN role TYPE VARCHAR')

    # ### end Alembic commands ###
