"""changed is_read to boolean

Revision ID: 95aa85b54f54
Revises: 8b2db5827f00
Create Date: 2026-02-25 22:28:34.665180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95aa85b54f54'
down_revision = '8b2db5827f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE chats ALTER COLUMN is_read TYPE BOOLEAN USING is_read::boolean')

    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE chats ALTER COLUMN is_read TYPE VARCHAR')

    # ### end Alembic commands ###

