"""Reset Password Table

Revision ID: da08ff9ec6bf
Revises: 2d4a462f5cef
Create Date: 2026-02-18 01:33:05.122661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da08ff9ec6bf'
down_revision = '2d4a462f5cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.execute("""
    ALTER TABLE password_resets 
    ALTER COLUMN is_used TYPE BOOLEAN USING is_used::boolean
"""):
    # ### end Alembic commands ###


